version: '3.9'

services:  
  sprecsample_db:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sprecsample_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - "./sample_db.sql:/docker-entrypoint-initdb.d/1.sql"
    container_name: sprecsample_db
